### PR TITLE
[WIP] Reorganize entire project around IBM Plex

### PR DESCRIPTION
**Pull request by seejamescode**
This is the pull request that will change this repo to revolve around IBM Plex instead of a combination with typography choices. This will focus the audience of the repo to the typeface community. When this pull request is merged, the repo will be renamed `ibm/plex`. A new repo called `ibm/type` will be created as a placeholder to redirect those still with the old link.

**Adds**
- IBM Plex Sans Condensed
- Cyrillic glyphs for IBM Plex Mono, Sans, and Serif
- Source files
- SCSS and CSS for _all_ weights and variants

**Removes**
- Typography CSS and SCSS (anything styling that would be included in a class)
- Intro letter found at https://ibm.github.io/type/

**To-Do**
- [ ] ~Add missing IBM Plex Sans Condensed Cyrillic splits provided by @BoldMonday~
- [x] Avoid Cyrillic font-face declarations for IBM Plex Sans Condensed since they are not available yet
- [x] Add unicode range for Cyrillic glyphs provided by @BoldMonday 
- [x] Add intro copy and image provided by @mjabbink 
- [x] Fix font weights for Text and heavier
- [ ] Travis config to automated releases during merge to master
- [x] Remove webpack example instead for `@ibm/typography` (@mjabbink’s decision)

**Zips to add to releases**
- `Mac (OpenType).zip`
- `PC (TrueType).zip`
- `Web.zip`
- `Source Code.zip`

**What to review right now:** The new [readme content found here](https://github.com/IBM/type/blob/plex/README.md). Please leave comments on this page. Anything @joshblack and @electrostaticfleece believe is off about the web development portion.

### CODE REVIEW

**Comment by BoldMonday** [comment]
The table with css weight values in the readme does not reflect the values stored in the fonts.

I don't know enough about css to judge if this is a problem.

Here are the values in the fonts themselves:
100 - IBM Plex Thin
100 - IBM Plex Thin Italic
200 - IBM Plex ExtraLight
200 - IBM Plex ExtraLight Italic
300 - IBM Plex Light
300 - IBM Plex Light Italic
400 - IBM Plex Regular
400 - IBM Plex Italic
450 - IBM Plex Text
450 - IBM Plex Text Italic
500 - IBM Plex Medium
500 - IBM Plex Medium Italic
600 - IBM Plex SemiBold
600 - IBM Plex SemiBold Italic
700 - IBM Plex Bold
700 - IBM Plex Bold Italic

**Comment by seejamescode** [comment]
Hey @BoldMonday, see the accepted values in [font-weight](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight) for CSS. It does not look like `450` is accepted. Would you like to send me new font files to reflect the table in the README?

**Comment by BoldMonday** [comment]
Hi @seejamescode We already followed the conventions with regard to weight values.

If you look at that [https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight](font-weight) page you will see that **Bold** should be **700**, not **800**.

Having 3 weights between Regular and Bold means that we had to choose 450 for Text weight.

**Comment by seejamescode** [comment]
Looking at [this blog post](http://bigelowandholmes.typepad.com/bigelow-holmes/2015/07/on-font-weight.html) it looks like x50 font weights will still work. I will adjust it as so.

**Comment by seejamescode** [comment]
Updated details above based on meeting with @mjabbink. @davelab6, please let me know if anything seems off to you.

**Comment by BoldMonday** [comment]
@seejamescode Plex Sans Condensed has no support for Cyrillic yet. Possibly in 2019.

**Comment by BoldMonday** [comment]
@seejamescode I propose a different name for *Woff.zip* as a release, since it should contain multiple formats: *woff*, *woff2*, and *eot*. Why not call it *Webfonts.zip*?

**Comment by mjabbink** [comment]
yes, good suggestion Paul.
 
 
Mike Abbink
—
Executive Creative Director,
Brand Experience and Design
+1 917 291 7516
E-mail: mjabbink@us.ibm.com
 
 
 
 
----- Original message -----From: Paul van der Laan <notifications@github.com>To: IBM/type <type@noreply.github.com>Cc: Mike Abbink <mjabbink@us.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [IBM/type] [WIP] Reorganize entire project around IBM Plex (#130)Date: Wed, Feb 14, 2018 3:49 AM 
@seejamescode I propose a different name for Woff.zip as a release, since it should contain multiple formats: woff, woff2, and eot. Why not call it Webfonts.zip?

**Comment by seejamescode** [comment]
Thanks @BoldMonday! Just updated the initial message to reflect both points.

**Comment by davelab6** [comment]
BTW when you rename a github repo it automatically sets up a redirect from
the old URLs

**Comment by seejamescode** [comment]
Hey @BoldMonday, please do one last review of [the readme](https://github.com/IBM/type/blob/plex/README.md) for us. @electrostaticfleece and @joshblack, please take one look over the [branch](https://github.com/IBM/type/tree/plex) to see if anything is off.

**Comment by BoldMonday** [comment]
Thanks for the update @seejamescode.

The current readme implies that there are only split webfonts for web developers, but there are the "unsplit" versions too (in woff, woff2 and eot format) which are superior when it comes to features and kerning. Hopefully you will find a way to mention them too?

Please also mention in the readme the availability of desktop versions in otf and ttf format. Do you agree @mjabbink?

**Comment by mjabbink** [comment]
Agree

—
Mike Abbink

Executive Creative Director,
Brand Experience and Design

+1 917 291 7516 mobile
mjabbink@us.ibm.com


—
Sent from my iPhone 
using IBM Verse

On Feb 21, 2018, 11:30:25 AM, notifications@github.com wrote:

**Comment by seejamescode** [comment]
Thanks y’all! Edits are reflected. We will be merging this afternoon.

**Pull request merged**
